package cn.edu.bnu.land.model;

// Generated 2013-10-14 10:05:29 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DbBackuprecord generated by hbm2java
 */
public class DbBackuprecord implements java.io.Serializable {

	private Integer version;
	private Date date;
	private Integer size;
	private String comment;

	public DbBackuprecord() {
	}

	public DbBackuprecord(Date date) {
		this.date = date;
	}

	public DbBackuprecord(Date date, Integer size, String comment) {
		this.date = date;
		this.size = size;
		this.comment = comment;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
