package cn.edu.bnu.land.model;

// Generated 2016-1-19 20:28:42 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projection generated by hbm2java
 */
@Entity
@Table(name = "projection", catalog = "tdlz")
public class Projection implements java.io.Serializable {

	private Integer id;
	private String projectNumber;
	private String projectAddress;
	private Date createTime;
	private String projectStatus;
	private Date endTime;
	private String projectDescription;
	private String files;

	public Projection() {
	}

	public Projection(String projectNumber, String projectAddress,
			Date createTime, String projectStatus, Date endTime,
			String projectDescription, String files) {
		this.projectNumber = projectNumber;
		this.projectAddress = projectAddress;
		this.createTime = createTime;
		this.projectStatus = projectStatus;
		this.endTime = endTime;
		this.projectDescription = projectDescription;
		this.files = files;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "projectNumber", length = 30)
	public String getProjectNumber() {
		return this.projectNumber;
	}

	public void setProjectNumber(String projectNumber) {
		this.projectNumber = projectNumber;
	}

	@Column(name = "projectAddress", length = 65535)
	public String getProjectAddress() {
		return this.projectAddress;
	}

	public void setProjectAddress(String projectAddress) {
		this.projectAddress = projectAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createTime", length = 10)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "projectStatus", length = 15)
	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endTime", length = 10)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "projectDescription", length = 200)
	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	@Column(name = "files", length = 10000)
	public String getFiles() {
		return this.files;
	}

	public void setFiles(String files) {
		this.files = files;
	}

}
