package cn.edu.bnu.land.model;

// Generated Oct 25, 2015 6:06:14 PM by Hibernate Tools 4.0.0

/**
 * TestUserId generated by hbm2java
 */
public class TestUserId implements java.io.Serializable {

	private int id;
	private String userName;
	private String password;
	private String email;
	private String telNum;
	private String address;
	private Boolean isEnable;
	private Integer age;

	public TestUserId() {
	}

	public TestUserId(int id) {
		this.id = id;
	}

	public TestUserId(int id, String userName, String password, String email,
			String telNum, String address, Boolean isEnable, Integer age) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.telNum = telNum;
		this.address = address;
		this.isEnable = isEnable;
		this.age = age;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelNum() {
		return this.telNum;
	}

	public void setTelNum(String telNum) {
		this.telNum = telNum;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Boolean getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestUserId))
			return false;
		TestUserId castOther = (TestUserId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getPassword() == castOther.getPassword()) || (this
						.getPassword() != null
						&& castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getTelNum() == castOther.getTelNum()) || (this
						.getTelNum() != null && castOther.getTelNum() != null && this
						.getTelNum().equals(castOther.getTelNum())))
				&& ((this.getAddress() == castOther.getAddress()) || (this
						.getAddress() != null && castOther.getAddress() != null && this
						.getAddress().equals(castOther.getAddress())))
				&& ((this.getIsEnable() == castOther.getIsEnable()) || (this
						.getIsEnable() != null
						&& castOther.getIsEnable() != null && this
						.getIsEnable().equals(castOther.getIsEnable())))
				&& ((this.getAge() == castOther.getAge()) || (this.getAge() != null
						&& castOther.getAge() != null && this.getAge().equals(
						castOther.getAge())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getTelNum() == null ? 0 : this.getTelNum().hashCode());
		result = 37 * result
				+ (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result
				+ (getIsEnable() == null ? 0 : this.getIsEnable().hashCode());
		result = 37 * result
				+ (getAge() == null ? 0 : this.getAge().hashCode());
		return result;
	}

}
