package cn.edu.bnu.land.model;

// Generated Oct 25, 2015 6:06:14 PM by Hibernate Tools 4.0.0

/**
 * TestUser generated by hbm2java
 */
public class TestUser implements java.io.Serializable {

	private TestUserId id;

	public TestUser() {
	}

	public TestUser(TestUserId id) {
		this.id = id;
	}

	public TestUserId getId() {
		return this.id;
	}

	public void setId(TestUserId id) {
		this.id = id;
	}

}
