package cn.edu.bnu.land.model;

// Generated Nov 4, 2015 9:01:24 PM by Hibernate Tools 4.0.0

/**
 * URoleRight generated by hbm2java
 */
public class URoleRight implements java.io.Serializable {

	private Integer id;
	private String roleId;
	private String rightId;

	public URoleRight() {
	}

	public URoleRight(String roleId, String rightId) {
		this.roleId = roleId;
		this.rightId = rightId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRightId() {
		return this.rightId;
	}

	public void setRightId(String rightId) {
		this.rightId = rightId;
	}

}
