/*
 * File: app/model/uOptLogModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.uOptLogModel', {
    extend: 'Ext.data.Model',
    alias: 'model.uOptLogModel',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'username'
        },
        {
            name: 'executetime'
        },
        {
            name: 'classname'
        },
        {
            name: 'functionname'
        },
        {
            name: 'parameters'
        }
    ]
});