/*
 * File: app/view/db_BlacklistWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.db_BlacklistWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.db_BlacklistWindow',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    height: 384,
    id: 'db_BlacklistWindow',
    width: 630,
    layout: 'fit',
    title: '企业信息',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'db_BlacklistWindowForm',
                    layout: 'auto',
                    bodyPadding: 10,
                    jsonSubmit: true,
                    items: [
                        {
                            xtype: 'fieldset',
                            title: '企业信息',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'blackwin_username',
                                    width: 400,
                                    fieldLabel: '用户名称',
                                    labelWidth: 70,
                                    name: 'username',
                                    submitValue: false,
                                    allowBlank: false,
                                    validateBlank: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'blackwin__companyname',
                                    width: 400,
                                    fieldLabel: '企业名称',
                                    labelWidth: 70,
                                    name: 'companyname',
                                    allowBlank: false,
                                    validateBlank: true
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'blackwin_reason',
                                    width: 400,
                                    fieldLabel: '加入原因',
                                    labelWidth: 70,
                                    name: 'reason',
                                    validateBlank: true,
                                    store: [
                                        '请选择..',
                                        '资质造假',
                                        '未按时交纳保证金',
                                        '竞拍违规',
                                        '金牌后拒签合同',
                                        '签合同后拒交价款，拒履行合同',
                                        '其他，(请输入..)'
                                    ],
                                    valueField: 'state'
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'blackwin_time',
                                    width: 400,
                                    fieldLabel: '加入时间',
                                    labelWidth: 70,
                                    name: 'time',
                                    allowBlank: false,
                                    validateBlank: true
                                },
                                {
                                    xtype: 'htmleditor',
                                    height: 120,
                                    id: 'blackwin_comment',
                                    fieldLabel: '备注说明',
                                    labelWidth: 70,
                                    name: 'comment'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: '取消',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 30
                                },
                                {
                                    xtype: 'button',
                                    text: '确认增加',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick1: function(button, e, eOpts) {
        var win = Ext.getCmp('db_BlacklistWindow');
        win.close();
    },

    onButtonClick: function(button, e, eOpts) {
        var win = Ext.getCmp('db_BlacklistWindow');
        var myform = Ext.getCmp('db_BlacklistWindowForm');

        if (myform.isValid())
        { // make sure the form contains valid data before submitting

            myform.submit({
                url : 'add_BlackCompany',
                success : function (form, action)
                {
                    Ext.Msg.alert('成功', '企业黑名单添加成功');

                    var mystore = Ext.StoreMgr.get('dbBlacklistStore'); //获得store对象
                    mystore.reload();
                    win.close();
                },
                failure: function(form, action){
                    Ext.Msg.alert('失败', '企业黑名单添加失败');
                    win.close();
                }
            });
        }
        else{
            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
        }

        return;
    }

});