/*
 * File: app/view/db_RoleRightSettingWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.db_RoleRightSettingWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.db_RoleRightSettingWindow',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    height: 358,
    id: 'db_RoleRightSettingWindow',
    width: 718,
    layout: 'fit',
    title: '用户角色设置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'db_RoleRightSettingGrid',
                    autoScroll: true,
                    store: 'uRightInfoStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 40,
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'rightName',
                            text: '权限名称'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'rightId',
                            text: '权限编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 100,
                            dataIndex: 'rightIndex',
                            text: '权限索引'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 250,
                            dataIndex: 'url',
                            text: '权限地址'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'description',
                            text: '描述'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'label',
                                    id: 'rrSet_roleId',
                                    text: '角色编号'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    handler: function() {
                                        var win = Ext.getCmp('db_UserRoleSettingWindow');
                                        win.close();
                                    },
                                    text: '取消'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 30
                                },
                                {
                                    xtype: 'button',
                                    handler: function() {
                                        var win = Ext.getCmp('db_RoleRightSettingWindow');

                                        var roleId = Ext.getCmp('rrSet_roleId').text;	//获取角色编号
                                        var grid = Ext.getCmp('db_RoleRightSettingGrid');		//获取表格grid
                                        var recordsSelected = grid.getSelectionModel().getSelection();	//获取选中的记录

                                        if(recordsSelected.length === 0){
                                            Ext.Msg.alert('提示','请先选择您要操作的行！');
                                            return;
                                        }else{
                                            //获取用户角色代码数组
                                            var  rightIds =new Array(recordsSelected.length);
                                            for(var i = 0;i<recordsSelected.length;i++){
                                                rightIds[i] = recordsSelected[i].get("rightId");
                                            }

                                            //更新该用户的角色信息
                                            Ext.Ajax.request(
                                            {
                                                url : 'update_RoleRight',
                                                params :
                                                {
                                                    roleId:roleId,
                                                    rightIds : rightIds
                                                },
                                                success : function (response){
                                                    Ext.Msg.alert('成功提示', '角色的权限信息更新成功。');
                                                    win.close();
                                                },
                                                failure : function (response){
                                                    Ext.Msg.alert('失败提示', '角色的权限信息更新失败，请刷新后重试。');
                                                }
                                            });



                                        }
                                    },
                                    text: '确定'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        afterrender: {
                            fn: me.onDb_RoleRightSettingGridAfterRender,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onDb_RoleRightSettingGridAfterRender: function(component, eOpts) {
        var roleId = Ext.getCmp('rrSet_roleId').text;

        //查询该用户的所有角色
        Ext.Ajax.request(
        {
            url : 'get_RoleRightList',
            params :
            {
                roleId : roleId
            },
            success : function (response){
                var result=Ext.decode(response.responseText);
                var roleIds = result.root;

                var store = Ext.StoreMgr.get('uRightInfoStore'); //获得store对象

                for(var index = 0;index < roleIds.length;index++){
                    var rightId = roleIds[index];
                    var record = store.findRecord("rightId", rightId, 0, true);
                    Ext.getCmp('db_RoleRightSettingGrid').getSelectionModel().select(record,true);
                }
            },
            failure : function (response){
                //failedResult();
                // Ext.Msg.alert('失败提示', '记录删除失败。');
            }
        });
    }

});