/*
 * File: app/view/db_UserPrivilegeManagerTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.db_UserPrivilegeManagerTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.db_UserPrivilegeManagerTab',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.resizer.Splitter',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel'
    ],

    id: 'db_UserPrivilegeManagerTab',
    layout: 'fit',
    title: '用户管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: '用户信息管理',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeyword_UserInfo',
                                            emptyText: '请输入搜索关键字'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/file_view0.png',
                                            text: '搜索',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_refresh.png',
                                            text: '刷新',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick1,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '添加',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick2,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '编辑',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick22,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '删除',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick221,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'splitter'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '设置部门',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick2211,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_role.png',
                                            text: '用户角色设置',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick22111,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'db_UserInfoGrid',
                                    autoScroll: true,
                                    store: 'uUserInfoStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 40,
                                            text: '序号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 70,
                                            dataIndex: 'userId',
                                            text: '用户编号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 100,
                                            dataIndex: 'userName',
                                            text: '用户名'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 100,
                                            dataIndex: 'deptId',
                                            text: '部门'
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            handler: function(grid, rowIndex, colIndex, actionItem, event, record, row) {
                                                var win = Ext.widget('db_UserRoleSettingWindow');
                                                win.show();

                                                //查询该用户的所有用户
                                                Ext.Ajax.request(
                                                {
                                                    url : 'del_UserInfoById',
                                                    params :
                                                    {
                                                        userId : userId
                                                    },
                                                    success : function (response){
                                                        Ext.Msg.alert('成功提示', '记录删除成功。');
                                                        //successResult();
                                                        var mystore = Ext.StoreMgr.get('uUserInfoStore');
                                                        mystore.load();
                                                    },
                                                    failure : function (response){
                                                        //failedResult();
                                                        // Ext.Msg.alert('失败提示', '记录删除失败。');
                                                    }
                                                });



                                                //		var keyword = record.get('userName').getValue();
                                                //
                                                //		var extra_params={
                                                //		    searchKeyword:keyword
                                                //		};
                                                //		Ext.apply(store.proxy.extraParams,extra_params);
                                                //
                                                //		if (colIndex === undefined || colIndex < 2) {
                                                //		    return;
                                                //		}
                                                //		var win = Ext.widget('db_UserInfoWindow');
                                                //		win.show();
                                                //
                                                //		//var form = Ext.widget('db_UserWindowForm');
                                                //		var form = Ext.getCmp('db_UserWindowForm');
                                                //		console.log("form:",form);
                                                //		form.loadRecord(record);
                                                //
                                                //
                                                //		//对显示的结果进行处理
                                                //		//注册日期的处理
                                                //		var registerdateField = Ext.getCmp('users_registerdatew');
                                                //		var value = registerdateField.getValue();
                                                //		var date = new Date(value);
                                                //		console.log('date',date);
                                                //		if(date instanceof Date){
                                                //		    var str = date.getFullYear()+'-'+(date.getMonth()+1)+'-'+date.getDate();
                                                //		    console.log('date2',str);
                                                //		    registerdateField.setValue(str);
                                                //		}
                                                //		//密码框的处理
                                                //		var pwdField = Ext.getCmp('users_passwordw');
                                                //		pwdField.setValue("");
                                            },
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var deptId = record.get('deptId');
                                                return '<div style="float:right; font-size: 13px; line-height: 1em;">' + deptId + '</div>'
                                            },
                                            width: 120,
                                            dataIndex: 'enabled',
                                            menuText: '',
                                            icon: 'images/table_edit.png'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 80,
                                            dataIndex: 'trueName',
                                            text: '真实姓名'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 120,
                                            dataIndex: 'email',
                                            text: '邮箱地址'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 100,
                                            dataIndex: 'mobileNum',
                                            text: '手机号码'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'phoneNum',
                                            text: '固定电话'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 200,
                                            dataIndex: 'description',
                                            text: '用户描述'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'registerdate',
                                            text: '注册日期',
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 60,
                                            dataIndex: 'enabled',
                                            text: '是否可用',
                                            falseText: '否',
                                            trueText: '是'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    }),
                                    listeners: {
                                        cellclick: {
                                            fn: me.onGridpanelCellClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            title: '角色信息管理',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeyword_roleInfo',
                                            emptyText: '请输入搜索关键字'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/file_view0.png',
                                            text: '搜索',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick3,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_refresh.png',
                                            text: '刷新',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick11,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '添加角色',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick21,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '编辑',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick212,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '删除',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick2121,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'splitter'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_right.png',
                                            text: '修改权限',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick21211,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'db_RoleInfoGrid',
                                    store: 'uRoleInfoStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 40,
                                            text: '序号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 120,
                                            dataIndex: 'roleNameCn',
                                            text: '角色名称'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            dataIndex: 'roleName',
                                            text: '角色标识'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 60,
                                            dataIndex: 'enabled',
                                            text: '是否启用',
                                            falseText: '否',
                                            trueText: '是'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 400,
                                            dataIndex: 'description',
                                            text: '描述'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            layout: 'fit',
                            title: '权限信息管理',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeyword_RightInfo',
                                            emptyText: '请输入搜索关键字'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/file_view0.png',
                                            text: '搜索',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick31,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_refresh.png',
                                            text: '刷新',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '添加权限',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick211,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '编辑',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick2111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '删除',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick21111,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'rightInfoGrid',
                                    autoScroll: true,
                                    store: 'uRightInfoStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 40,
                                            text: '序号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 200,
                                            dataIndex: 'rightName',
                                            text: '权限名称'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'rightId',
                                            text: '权限编号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 150,
                                            dataIndex: 'url',
                                            text: '权限地址'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 60,
                                            dataIndex: 'enabled',
                                            text: '是否启用',
                                            falseText: '否',
                                            trueText: '是'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 400,
                                            dataIndex: 'description',
                                            text: '描述'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            layout: 'fit',
                            title: '部门信息管理',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'searchKeyword_DeptInfo',
                                            emptyText: '请输入搜索关键字'
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/file_view0.png',
                                            text: '搜索',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick31111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_refresh.png',
                                            text: '刷新',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick111111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '添加新部门',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick211111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '编辑',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick2111111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            icon: 'images/table_add.png',
                                            text: '删除',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick21111111,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id: 'deptInfoGrid',
                                    autoScroll: true,
                                    store: 'uDeptInfoStore',
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 200,
                                            dataIndex: 'deptName',
                                            text: '部门名称'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'deptId',
                                            text: '部门编号'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            width: 50,
                                            dataIndex: 'enabled',
                                            text: '可用',
                                            falseText: '否',
                                            trueText: '是'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 400,
                                            dataIndex: 'description',
                                            text: '描述'
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var getKeyword = Ext.getCmp('searchKeyword_UserInfo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('uUserInfoStore'); //获得store对象
        //在load事件中添加参数
        mystore.load(
        {
            params :
            {
                searchKeyword : getKeyword
            }
        }
        );

    },

    onButtonClick1: function(button, e, eOpts) {
        Ext.getCmp('searchKeyword_UserInfo').setValue('');
        var mystore = Ext.StoreMgr.get('uUserInfoStore'); //获得store对象
        mystore.load();

    },

    onButtonClick2: function(button, e, eOpts) {
        var win = Ext.widget('db_UserInfoAddWindow');
        win.show();
    },

    onButtonClick22: function(button, e, eOpts) {
        var grid = Ext.getCmp('db_UserInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else if(record.length >1){
            Ext.Msg.alert('提示','您只能编辑一个用户，请重新选择。');
            return;
        }else {

            var win = Ext.widget('db_UserInfoWindow');
            win.show();

            var form = Ext.getCmp('db_UserWindowForm');
            form.loadRecord(record[0]);

            //对显示的结果进行处理
            //注册日期的处理
            var registerdateField = Ext.getCmp('users_registerdatew');
            var value = registerdateField.getValue();
            var date = new Date(value);
            console.log('date',date);
            if(date instanceof Date){
                var str = date.getFullYear()+'-'+(date.getMonth()+1)+'-'+date.getDate();
                console.log('date2',str);
                registerdateField.setValue(str);
            }
            //密码框的处理
            var pwdField = Ext.getCmp('users_passwordw');
            pwdField.setValue("");
        }



    },

    onButtonClick221: function(button, e, eOpts) {
        var grid = Ext.getCmp('db_UserInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else{
            var  userIds =new Array(record.length);
            var msg = '';
            for(var i = 0;i<record.length;i++){
                userIds[i] = record[i].get("userId");
                msg += record[i].get("userName") + '<br/>';
            }

            Ext.Msg.confirm('提示', '您正在删除以下用户：<br/>' + msg+'确认删除？', getResult);
            function getResult(confirm)
            {
                if (confirm == "yes"){
                    Ext.Ajax.request(
                        {
                            url : 'del_UserInfoById',
                            params :
                            {
                                userIds : userIds
                            },
                            success : function (response){
                                Ext.Msg.alert('成功提示', '记录删除成功。');
                                //successResult();
                                var mystore = Ext.StoreMgr.get('uUserInfoStore');
                                mystore.load();
                            },
                            failure : function (response){
                                //failedResult();
                                // Ext.Msg.alert('失败提示', '记录删除失败。');
                            }
                        });
                }
            }
        }



    },

    onButtonClick2211: function(button, e, eOpts) {
        var grid = Ext.getCmp('db_UserInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0 ){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else if(record.length < 1){
            Ext.Msg.alert('提示','您只能同时编辑一个用户信息，请重新选择。');
            return;
        }else{
            var win = Ext.widget('db_UserRoleSettingWindow');
            //设置window中的用户名，便于查询
            var userName = record[0].get('userName');
            Ext.getCmp('urSet_userName').setText(userName);
            win.show();

        }



    },

    onButtonClick22111: function(button, e, eOpts) {
        var grid = Ext.getCmp('db_UserInfoGrid');		//获取表格grid
        var recordsSelected = grid.getSelectionModel().getSelection();	//获取选中的记录

        if(recordsSelected.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的用户！');
            return;
        }else if(recordsSelected.length > 1){
            Ext.Msg.alert('提示','请选中单个用户进行操作！');
            return;
        }else{
            var win = Ext.widget('db_UserRoleSettingWindow');

            //设置window中的用户名，便于查询
            var userName = recordsSelected[0].get('userName');
            Ext.getCmp('urSet_userName').setText(userName);

            //显示window
            win.show();
        }
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        //console.log('this is cellclick');
        //console.log('tableview:',tableview);
        //console.log('td:',td);
        //console.log('cellIndex:',cellIndex);
        //console.log('record:',record);
        //console.log('tr:',tr);
        //console.log('rowIndex:',rowIndex);


    },

    onButtonClick3: function(button, e, eOpts) {
        var getKeyword = Ext.getCmp('searchKeyword_roleInfo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('uRoleInfoStore'); //获得store对象
        //在load事件中添加参数
        mystore.load({
            params :
            {
                searchKeyword : getKeyword,
                enabled:"true"
            }
        });
    },

    onButtonClick11: function(button, e, eOpts) {
        Ext.getCmp('searchKeyword_roleInfo').setValue('');
        var mystore = Ext.StoreMgr.get('uRoleInfoStore'); //获得store对象
        mystore.load();

    },

    onButtonClick21: function(button, e, eOpts) {
        var win = Ext.widget('db_RoleInfoAddWindow');
        win.show();

    },

    onButtonClick212: function(button, e, eOpts) {
        var grid = Ext.getCmp('db_RoleInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else if(record.length >1){
            Ext.Msg.alert('提示','您只能编辑一个角色信息，请重新选择。');
            return;
        }else {

            var win = Ext.widget('db_RoleInfoWindow');
            win.show();

            var form = Ext.getCmp('db_RoleInfoWindowForm').getForm();
            form.loadRecord(record[0]);
        }
    },

    onButtonClick2121: function(button, e, eOpts) {
        var grid = Ext.getCmp('db_RoleInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else{
            var  roleIds =new Array(record.length);
            var msg = '';
            for(var i = 0;i<record.length;i++){
                roleIds[i] = record[i].get("roleId");
                msg += record[i].get("roleName") + '<br/>';
            }

            Ext.Msg.confirm('提示', '您正在删除以下角色：<br/>' + msg+'确认删除？', getResult);
            function getResult(confirm)
            {
                console.log('confirm:', confirm);
                if (confirm == "yes"){

                    Ext.Ajax.request(
                        {
                            url : 'del_RoleInfoById',
                            params :
                            {
                                roleIds : roleIds
                            },
                            success : function (response){
                                Ext.Msg.alert('成功提示', '角色删除成功。');
                                var mystore = Ext.StoreMgr.get('uRoleInfoStore');
                                mystore.load();
                            },
                            failure : function (response){

                            }
                        });
                }
            }
        }
    },

    onButtonClick21211: function(button, e, eOpts) {
        var grid = Ext.getCmp('db_RoleInfoGrid');		//获取表格grid
        var recordsSelected = grid.getSelectionModel().getSelection();	//获取选中的记录

        if(recordsSelected.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的角色！');
            return;
        }else if(recordsSelected.length > 1){
            Ext.Msg.alert('提示','请选中单个角色进行操作！');
            return;
        }else{
            var win = Ext.widget('db_RoleRightSettingWindow');

            //设置window中的角色id，便于查询
            var roleId = recordsSelected[0].get('roleId');
            Ext.getCmp('rrSet_roleId').setText(roleId);

            //显示window
            win.show();
        }

    },

    onButtonClick31: function(button, e, eOpts) {
        var getKeyword = Ext.getCmp('searchKeyword_RightInfo').getValue();
        //console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('uRightInfoStore'); //获得store对象
        //在load事件中添加参数
        mystore.load({
            params :{
                searchKeyword : getKeyword,
                limit:'300'
            }
        });

    },

    onButtonClick111: function(button, e, eOpts) {
        Ext.getCmp('searchKeyword_RightInfo').setValue('');
        var mystore = Ext.StoreMgr.get('uRightInfoStore'); //获得store对象
        mystore.load();

    },

    onButtonClick211: function(button, e, eOpts) {
        //取得上一级部门id
        var grid = Ext.getCmp('rightInfoGrid');
        var record = grid.getSelectionModel().getSelection();
        if(record.length === 0){
            Ext.MessageBox.confirm('提示','添加新的权限需要先指定上一级权限，如果您没有在列表中勾选上一级权限，</br>那么您添加的权限为最高级别。确定添加？', function(btn){
                if(btn == "yes"){
                    doShowWin(0);
                }
            });
            return;

        }else{
            doShowWin(1);
        }

        function doShowWin(level){
            console.log('level:',level);
            var win = Ext.widget('db_RightInfoAddWindow');
            win.show();

            var rightIdField = Ext.getCmp('wAdd_parentRightId');
            var rightNameField = Ext.getCmp('wAdd_parentRightName');
            //对显示的内容进行处理
            switch(level){
                case 0:	//如果没有上级部门
                    rightIdField.setValue("0000000000");	//如果没有上一级部门，则设为0
                    rightNameField.disable();
                    break;
                case 1:	//如果有上级部门
                    var  rightId = record[0].get("rightId");	//取得上级部门id
                    rightIdField.setValue(rightId);
                    //对部门名称进行处理
                    var rightName = record[0].get("rightName");	//取得上级部门名称

                    var index = rightName.lastIndexOf("&nbsp;");
                    if(index >= 0){
                        var substr = rightName.substring(index+6,rightName.length);
                        rightNameField.setValue(substr);
                    }
                    break;
            }

        }
    },

    onButtonClick2111: function(button, e, eOpts) {
        var grid = Ext.getCmp('rightInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else if(record.length >1){
            Ext.Msg.alert('提示','您只能编辑一个权限信息，请重新选择。');
            return;
        }else {
            var win = Ext.widget('db_RightInfoWindow');
            win.show();

            var form = Ext.getCmp('db_RightInfoWindowForm');
            form.loadRecord(record[0]);

            //对显示的内容进行处理
            //对权限名称进行处理
            var rightNameField = Ext.getCmp('w_rightName');
            var value = rightNameField.getValue();
            var index = value.lastIndexOf("&nbsp;");
            console.log(index);
            if(index>=0){
                var substr = value.substring(index+6,value.length);
                rightNameField.setValue(substr);
            }
        }


    },

    onButtonClick21111: function(button, e, eOpts) {
        var grid = Ext.getCmp('rightInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else{
            var  rightIds =new Array(record.length);
            var msg = '';
            for(var i = 0;i<record.length;i++){
                rightIds[i] = record[i].get("rightId");
                //去除权限名称的空格
                var rightName = record[i].get('rightName');
                var index = rightName.lastIndexOf("&nbsp;");
                var substr;
                if(index>=0){
                    substr = rightName.substring(index+6,rightName.length);
                }
                msg += substr + '<br/>';
            }

            Ext.Msg.confirm('提示', '您正在删除以下权限：<br/>' + msg+'确认删除？', getResult);
            function getResult(confirm)
            {
                if (confirm == "yes"){
                    Ext.Ajax.request(
                        {
                            url : 'del_RightInfoById',
                            params :
                            {
                                rightIds : rightIds
                            },
                            success : function (response){
                                Ext.Msg.alert('成功提示', '权限删除成功。');
                                //successResult();
                                var mystore = Ext.StoreMgr.get('uRightInfoStore');
                                mystore.load();
                            },
                            failure : function (response){
                                //failedResult();
                                // Ext.Msg.alert('失败提示', '记录删除失败。');
                            }
                        });
                }
            }
        }
    },

    onButtonClick31111: function(button, e, eOpts) {
        var getKeyword = Ext.getCmp('searchKeyword_DeptInfo').getValue();
        console.log("keyword:",getKeyword);
        var mystore = Ext.StoreMgr.get('uDeptInfoStore'); //获得store对象
        //在load事件中添加参数
        mystore.load();

    },

    onButtonClick111111: function(button, e, eOpts) {
        Ext.getCmp('searchKeyword_DeptInfo').setValue('');
        var mystore = Ext.StoreMgr.get('uDeptInfoStore'); //获得store对象
        mystore.reload();

    },

    onButtonClick211111: function(button, e, eOpts) {
        //取得上一级部门id
        var grid = Ext.getCmp('deptInfoGrid');
        var record = grid.getSelectionModel().getSelection();
        if(record.length === 0){
            Ext.MessageBox.confirm('提示','添加新的部门需要先指定上一级部门，如果您没有在列表中勾选上一级部门，</br>那么您添加的部门为最高级别。确定添加？', function(btn){
                if(btn == "yes"){
                    doShowWin(0);
                }
            });
            return;

        }else{
            doShowWin(1);
        }
        function doShowWin(level){
            console.log('level:',level);
            var win = Ext.widget('db_DeptInfoAddWindow');
            win.show();

            var deptIdField = Ext.getCmp('deptAdd_parentDeptId');
            //对显示的内容进行处理
            switch(level){
                case 0:	//如果没有上级部门
                deptIdField.setValue("0000000000");	//如果没有上一级部门，则设为0
                break;
                case 1:	//如果有上级部门
                var  deptId = record[0].get("deptId");	//取得上级部门id
                var deptName = record[0].get("deptName");	//取得上级部门名称
                deptIdField.setValue(deptId);
                //对部门名称进行处理
                var deptNameField = Ext.getCmp('deptAdd_parentDeptName');
                var index = deptName.lastIndexOf("&nbsp;");
                if(index >= 0){
                    var substr = deptName.substring(index+6,deptName.length);
                    deptNameField.setValue(substr);
                }
                break;
            }

        }
    },

    onButtonClick2111111: function(button, e, eOpts) {
        var grid = Ext.getCmp('deptInfoGrid');

        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else if(record.length >1){
            Ext.Msg.alert('提示','您只能编辑一个部门信息，请重新选择。');
            return;
        }else {
            var win = Ext.widget('db_DeptInfoWindow');
            win.show();

            var form = Ext.getCmp('db_DeptInfoWindowForm');
            form.loadRecord(record[0]);

            //对显示的内容进行处理
            //对部门名称进行处理
            var deptNameField = Ext.getCmp('deptWindow_deptName');
            var value = deptNameField.getValue();
            var index = value.lastIndexOf("&nbsp;");
            console.log(index);
            if(index>=0){
                var substr = value.substring(index+6,value.length);
                deptNameField.setValue(substr);
            }
        }


    },

    onButtonClick21111111: function(button, e, eOpts) {
        var grid = Ext.getCmp('deptInfoGrid');
        var record = grid.getSelectionModel().getSelection();

        if(record.length === 0){
            Ext.Msg.alert('提示','请先选择您要操作的行！');
            return;
        }else{
            var  deptIds =new Array(record.length);
            var msg = '';
            for(var i = 0;i<record.length;i++){
                deptIds[i] = record[i].get("deptId");
                //去除权限名称的空格
                //去除名称的空格
                var deptName = record[i].get('deptName');
                var index = deptName.lastIndexOf("&nbsp;");
                var substr = '';
                if(index>=0){
                    substr = deptName.substring(index+6,deptName.length);
                }
                msg += substr + '<br/>';
            }

            Ext.Msg.confirm('提示', '您正在删除以下部门：<br/>' + msg+'确认删除？', getResult);
            function getResult(confirm)
            {
                if (confirm == "yes"){
                    Ext.Ajax.request(
                    {
                        url : 'del_DeptInfoById',
                        params :
                        {
                            deptIds : deptIds
                        },
                        success : function (response){
                            Ext.Msg.alert('成功提示', '记录删除成功。');
                            //successResult();
                            var mystore = Ext.StoreMgr.get('uDeptInfoStore');
                            mystore.load();
                        },
                        failure : function (response){
                            //failedResult();
                            // Ext.Msg.alert('失败提示', '记录删除失败。');
                        }
                    });
                }
            }
        }





    }

});