/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.infoArticleJYXCTab',
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Label',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    id: 'myViewPort',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 150,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'image',
                            src: 'images/title.png'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    href: '/tdlz/',
                                    text: '农村土地交易中心'
                                },
                                {
                                    xtype: 'button',
                                    href: '/tdjygl/',
                                    text: '电子交易系统'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'label',
                                    height: 13,
                                    html: '',
                                    text: '欢迎：'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //打开用户信息编辑tab
                                        var xtype = "db_UserInfoEditTab";
                                        var tabPanel = Ext.getCmp('myTabPanel');
                                        tabPanel.removeAll(true);
                                        tabPanel.add(Ext.widget(xtype));

                                        //从store中获取对应的用户信息，填充到界面
                                        var userInfoEditForm = Ext.getCmp('db_UserInfoEditForm').getForm();	//获取form
                                        var userStore = Ext.StoreMgr.get('uUserInfoStore');			//获取store
                                        var btn_username = Ext.getCmp('btn_username');				//获取按钮
                                        var username = btn_username.getText();						//获取按钮文字（用户名）
                                        var record = userStore.findRecord('userName', username) ;	//获取record

                                        userInfoEditForm.loadRecord(record);						//填充到界面

                                        //处理界面填充的内容
                                        //注册日期的处理
                                        var registerdateField = Ext.getCmp('users_registerdate');
                                        var value = registerdateField.getValue();
                                        var date = new Date(value);
                                        if(date instanceof Date){
                                            var str = date.getFullYear()+'-'+(date.getMonth()+1)+'-'+date.getDate();
                                            registerdateField.setValue(str);
                                        }
                                        //密码框的处理
                                        var pwdField = Ext.getCmp('users_password');
                                        pwdField.setValue("");
                                    },
                                    id: 'btn_username',
                                    text: '用户'
                                },
                                {
                                    xtype: 'button',
                                    href: 'j_spring_security_logout',
                                    hrefTarget: '_parent',
                                    text: '退出'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    width: 150,
                    layout: 'accordion',
                    collapsible: true,
                    title: '管理面板',
                    items: [
                        {
                            xtype: 'treepanel',
                            id: 'tree_infoPubManager',
                            title: '信息管理与发布',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'infoArticleJYXCTab',
                                        text: '建言献策',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleWFJCTab',
                                        text: '违法监察',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleBSZNTab',
                                        text: '办事指南',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleYWJSTab',
                                        text: '业务介绍',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleFLFGTab',
                                        text: '法律法规',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleZCJDTab',
                                        text: '政策解读',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleBZGFTab',
                                        text: '标准规范',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleCJWTTab',
                                        text: '常见问题解答',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_xianzhuang',
                            title: '现状',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'fieldWatchPanel',
                                        text: '现场调查',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'fieldLhdPanel',
                                        text: '撂荒地查询',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'fieldFqdPanel',
                                        text: '废弃地查询',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'fieldKxcPanel',
                                        text: '空心村查询',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange3,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_guihua',
                            title: '规划',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: '',
                                        text: '项目与规划',
                                        icon: '',
                                        children: [
                                            //{
                                            //    id: 302,
                                            //    text: '项目管理',
                                            //    icon: '',
                                            //    leaf: true
                                            //}, 
                                            {
                                                id: 309,
                                                text: '项目资料管理',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 308,
                                                text: '项目资料管理',
                                                icon: '',
                                                leaf: true
                                            }
                                            //{
                                            //    id: 303,
                                            //    text: '规划拆迁区域',
                                            //    icon: '',
                                            //    leaf: true
                                            //}
                                            //, {
                                            //    id: 304,
                                            //    text: '现状冲突房屋',
                                            //    icon: '',
                                            //    leaf: true
                                            //}
                                            //,
                                            //                                            {
                                            //                                                id: 102,
                                            //                                                text: '任务管理',
                                            //                                                icon: '',
                                            //                                                leaf: true
                                            //                                            },
                                        ]
                                    },
                                    {
                                        id: '',
                                        text: '公告及意见',
                                        icon: '',
                                        children: [
                                            {
                                                id: 601,
                                                text: '查看公告',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 602,
                                                text: '添加公告',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 603,
                                                text: '发表意见',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 604,
                                                text: '查看意见',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 605,
                                                text: '意见统计',
                                                icon: '',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        //    id: '',
                                        //    text: '复垦申请管理',
                                        //    icon: '',
                                        //    children: [{
                                        //        id: 401,
                                        //        text: '填写复垦申请',
                                        //        icon: '',
                                        //        leaf: true
                                        //    }, {
                                        //        id: 402,
                                        //        text: '上传权利证明',
                                        //        icon: '',
                                        //        leaf: true
                                        //    }, {
                                        //        id: 403,
                                        //       text: '撤销及修改申请',
                                        //        icon: '',
                                        //        leaf: true
                                        //    }, {
                                        //        id: 404,
                                        //        text: '审核申请',
                                        //        icon: '',
                                        //       leaf: true
                                        //    }, {
                                        //        id: 405,
                                        //        text: '查看申请状态',
                                        //        icon: '',
                                        //        leaf: true
                                        //    }]
                                        //}, {
                                        id: 501,
                                        text: '录入拆迁面积',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 502,
                                        text: '农户拆迁信息确认',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 503,
                                        text: '农户补偿信息确认',
                                        icon: '',
                                        leaf: true,
                                        
                                    },
                                    {
                                        id: 505,
                                        text: '查看农户拆确认汇总表',
                                        icon: '',
                                        leaf: true,
                                        
                                    },
                                    {
                                        id: '',
                                        text: '入库备案',
                                        icon: '',
                                        children: [
                                            {
                                                id: 901,
                                                text: '上传备案资料',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 902,
                                                text: '审核备案资料',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 903,
                                                text: '查看审核状态',
                                                icon: '',
                                                leaf: true
                                            }
                                        ]
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange4,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_chaiqian',
                            title: '拆迁',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 504,
                                        text: '查看拆迁日志',
                                        icon: '',
                                        leaf: true,
                                        
                                    },
                                    {
                                        id: '',
                                        text: '监测监控',
                                        icon: '',
                                        children: [
                                            {
                                                id: 701,
                                                text: '空间监测',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 702,
                                                text: '补偿监测',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 703,
                                                text: '安置监测',
                                                icon: '',
                                                leaf: true
                                            },
                                            
                                        ]
                                    },
                                    {
                                        id: '',
                                        text: '预警管理',
                                        icon: '',
                                        children: [
                                            {
                                                id: 801,
                                                text: '预警规则管理',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 802,
                                                text: '预警日志管理',
                                                icon: '',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        id: 1001,
                                        text: '评估',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange5,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_fukenyanshou',
                            title: '复垦及验收',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'manageProject',
                                        text: '项目管理',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'syrSchemeShow',
                                        text: '复垦信息公告',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'syrDataManagement',
                                        text: '复垦过程监控',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'acceptApply',
                                        text: '验收申请',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'fk_fukenyanshoupingjia',
                                        text: '复垦验收评价',
                                        icon: '',
                                        children: [
                                            {
                                                id: 'EvaluateSelectProject',
                                                text: '质量评价',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 'EvaluateReport',
                                                text: '复垦评价报告',
                                                icon: '',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        id: 'RegulatoryWarning',
                                        text: '监管预警',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange6,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_jiaoyi',
                            title: '交易',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'TaishiFind',
                                        text: '交易态势查询',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiPrice',
                                        text: '按交易价格分析',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiVolume',
                                        text: '按交易量分析',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiNumber',
                                        text: '按交易次数分析',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiArea',
                                        text: '按交易区域分析',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiAlarm',
                                        text: '交易态势异常分析',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'abnmDkTransSupervisionTab',
                                        text: '交易风险预警',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange7,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_shiyong',
                            title: '使用',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'use_MonitoringSampling',
                                        text: '流转后土地用地抽样监测',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'use_MonitorResult',
                                        text: '监测抽样结果',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange8,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_jianguan',
                            title: '监管',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'abnmWholeSupervisionTab',
                                        text: '全过程异常监管',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'jg_yijianzhengji',
                                        text: '意见征集与舆情分析',
                                        children: [
                                            {
                                                id: 'infoVoteTab',
                                                text: '网上投票管理',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 'infoLetterTab',
                                                text: '群众来信管理',
                                                icon: '',
                                                leaf: true
                                            },
                                            {
                                                id: 'infoReportTab',
                                                text: '违规流转投诉举报管理',
                                                icon: '',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        id: 'abnmXunChaTab',
                                        text: '现场巡查管理',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'abnmSupInfoTab',
                                        text: '监察信息查询统计',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange2,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            id: 'tree_shujuguanli',
                            title: '数据管理',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'db_BackupRecoveryData',
                                        text: '备份与恢复',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'db_UserPrivilegeManagerTab',
                                        text: '用户管理',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'db_SystemLogTab',
                                        text: '系统运行日志',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: 'db_BlacklistTab',
                                        text: '企业黑名单',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange10,
                                    scope: me
                                },
                                beforeexpand: {
                                    fn: me.onTreepanelBeforeExpand,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    id: 'myTabPanel',
                    items: [
                        {
                            xtype: 'infoArticleJYXCTab'
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onMyViewPortAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onTreepanelSelectionChange1: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange3: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange4: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');

        switch (xtype) {
            case 302:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('proj'));
                Ext.getCmp("proj").getLayout().setActiveItem(1);
                break;
            case 309:
                var proView = Ext.widget('projectionFile');
                console.log("view:",proView);
                tabPanel.removeAll(true);
                tabPanel.add(proView);
                //Ext.getCmp("projectionFile").getLayout().setActiveItem(1);
                //var xtype = selected[0].get('id');
                //var tabPanel = Ext.getCmp('myTabPanel');
                //tabPanel.removeAll(true);
                //tabPanel.add(Ext.widget(xtype));

                break;
            case 308:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('projection_map'));
                Ext.getCmp("projection_map").getLayout().setActiveItem(2);
                break;
            case 303:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('proj'));
                var head = document.getElementsByTagName('head')[0];
                var script = document.createElement("script");
                script.type = "text/javascript";
                script.src = "MyMap/ProjectMap.js";
                head.appendChild(script);
                Ext.getCmp("proj").getLayout().setActiveItem(2);
                break;
            case 304:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('proj'));
                Ext.getCmp("proj").getLayout().setActiveItem(4);
                break;
            case 102:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('main'));
                Ext.getCmp("main").getLayout().setActiveItem(2);
                break;
            case 401:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('application'));
                Ext.getCmp("application").getLayout().setActiveItem(0);
                break;
            case 402:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('application'));
                Ext.getCmp("application").getLayout().setActiveItem(1);
                break;
            case 403:

                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('application'));
                var appStore = Ext.create('Ext.data.Store', {

                    proxy: {
                        // load using HTTP
                        type: 'ajax',
                        url: 'showAppByID.action',
                        // the return will be XML, so lets set up a reader
                        reader: {
                            type: "json",
                            root: "results",
                            totalProperty: 'totalCount'
                        },
                        actionMethods: {
                            read: 'POST'
                        },
                        writer: {
                            type: "json"
                        }
                    },
                    listeners: {
                        beforeload: function() {
                            msgTip = Ext.MessageBox.show({
                                title: '提示',
                                width: 250,
                                msg: '加载中,请稍后......'
                            });
                        }
                    },
                    fields: [{
                        name: 'name',
                        type: 'string',
                        useNull: true
                    }, {
                        name: 'card',
                        type: 'string'
                    }, {
                        name: 'address',
                        type: 'string'
                    }, {
                        name: 'applicationAddress',
                        type: 'string'
                    }, {
                        name: 'productID',
                        type: 'string'
                    }, {
                        name: 'phone',
                        type: 'string'
                    }, {
                        name: 'totalArea',
                        type: 'auto'
                    }, {
                        name: 'bulidArea',
                        type: 'auto'
                    }, {
                        name: 'productDate',
                        type: 'date',
                        mapping: 'productDate.time',
                        dateFormat: 'time'
                    }, {
                        name: 'applicationDate',
                        type: 'date',
                        mapping: 'applicationDate.time',
                        dateFormat: 'time'
                    }, {
                        name: 'north',
                        type: 'auto'
                    }, {
                        name: 'south',
                        type: 'auto'
                    }, {
                        name: 'west',
                        type: 'auto'
                    }, {
                        name: 'east',
                        type: 'auto'
                    }, {
                        name: 'work',
                        type: 'string'
                    }, {
                        name: 'afterUse',
                        type: 'string'
                    }, {
                        name: 'belongUse',
                        type: 'string'
                    }, {
                        name: 'reword',
                        type: 'string'
                    }, {
                        name: 'isAgreeSelf',
                        type: 'string'
                    }, {
                        name: 'isAgreeVillage',
                        type: 'string'
                    }, {
                        name: 'isAgreeTown',
                        type: 'string'
                    }, {
                        name: 'content',
                        type: 'string'
                    }]

                });



                appStore.load({
                    callback: function(records, options, success) {


                        //遍历store
                        appStore.each(function(record) {

                            //重写radiogroup的 setValue()方法。
                            Ext.override(Ext.form.RadioGroup, {
                                setValue: function(v) {
                                    v = v.replace(/^\s+|\s+$/g, "");
                                    this.items.each(function(item, index, length) {
                                        if (v == item.boxLabel) item.checked = true;
                                    });
                                }
                            });
                            Ext.getCmp("appliName1").setValue(record.get("name"));
                            Ext.getCmp("appliID1").setValue(record.get("card"));
                            Ext.getCmp("appliAddress1").setValue(record.get("address"));
                            Ext.getCmp("appliLocate1").setValue(record.get("applicationAddress"));
                            Ext.getCmp("appliTel1").setValue(record.get("phone"));
                            Ext.getCmp("appliNumber1").setValue(record.get("productID"));
                            Ext.getCmp("areaTotle1").setValue(record.get("totalArea"));
                            Ext.getCmp("area1").setValue(record.get("bulidArea"));
                            Ext.getCmp("startTime1").setValue(record.get("productDate"));
                            Ext.getCmp("appliTime1").setValue(record.get("applicationDate"));

                            //四至范围
                            Ext.getCmp("toNorth1").setValue(record.get("north"));
                            Ext.getCmp("toSouth1").setValue(record.get("south"));
                            Ext.getCmp("toWest1").setValue(record.get("west"));
                            Ext.getCmp("toEast1").setValue(record.get("east"));


                            Ext.getCmp("mode1").setValue(record.get("work"));
                            Ext.getCmp("usage1").setValue(record.get("afterUse"));
                            Ext.getCmp("ownership1").setValue(record.get("belongUse"));
                            Ext.getCmp("payments1").setValue(record.get("reword"));
                            Ext.getCmp("agreement3").setValue(record.get("isAgreeSelf"));
                            Ext.getCmp("agreement4").setValue(record.get("isAgreeVillage"));
                            Ext.getCmp("agreement5").setValue(record.get("isAgreeTown"));

                            Ext.getCmp("contentOthers1").setValue(record.get("content"));


                        });

                        msgTip.hide(); // 加载完成，关闭提示框
                        Ext.getCmp("application").getLayout().setActiveItem(2);

                    }
                });


                break;

            case 404:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('application'));
                Ext.getCmp("application").getLayout().setActiveItem(3);
                break;
            case 405:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('application'));
                Ext.getCmp("application").getLayout().setActiveItem(4);
                break;

            case 601:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('notice'));
                Ext.getCmp("notice").getLayout().setActiveItem(0);
                Ext.getCmp("allNotice").getLayout().setActiveItem(0);
                break;
            case 602:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('notice'));
                if (Ext.getCmp('noticeEnclosure') !== undefined) {

                    Ext.getCmp('noticeEnclosure').getComponent(0).setRawValue("");

                }
                Ext.getCmp("notice").getLayout().setActiveItem(1);
                break;
            case 603:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('notice'));
                Ext.getCmp("notice").getLayout().setActiveItem(2);
                break;
            case 604:

                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('notice'));
                Ext.getCmp("notice").getLayout().setActiveItem(3);
                Ext.getCmp("gridviewShowSug").getStore().load({
                    params: {
                        start: 0,
                        limit: 2,
                        date: "",
                        noticeID: "1"
                    }
                });
                break;

            case 605:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('notice'));
                Ext.getStore('point').reload();
                Ext.getCmp("notice").getLayout().setActiveItem(4);
                break;

            case 501:

                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('reclProc'));
                var store = Ext.getCmp("writeArea").getStore();
                store.load({
                    params: {
                        flag: ""
                    },
                    callback: function(records, options, success) {
                        Ext.getCmp("ReclProc").getLayout().setActiveItem(0);
                    }
                });
                break;
            case 502:

                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('reclProc'));
                var store = Ext.getCmp("writeArea").getStore();
                store.load({
                    params: {
                        flag: "1"
                    },
                    callback: function(records, options, success) {
                        Ext.getCmp("ReclProc").getLayout().setActiveItem(1);
                    }
                });
                break;
            case 503:

                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('reclProc'));
                var store = Ext.getCmp("writeArea").getStore();
                store.load({
                    params: {
                        flag: "1"
                    },
                    callback: function(records, options, success) {
                        Ext.getCmp("ReclProc").getLayout().setActiveItem(2);
                    }
                });
                break;
            case 505:

                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('reclProc'));
                var store = Ext.getCmp("writeArea").getStore();
                store.load({
                    params: {
                        flag: ""
                    },
                    callback: function(records, options, success) {
                        Ext.getCmp("ReclProc").getLayout().setActiveItem(6);
                    }
                });
                break;
            case 901:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('recFile'));
                Ext.getCmp("RecFile").getLayout().setActiveItem(0);
                break;
            case 902:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('recFile'));
                Ext.getCmp("RecFile").getLayout().setActiveItem(1);
                break;
            case 903:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('recFile'));
                Ext.getCmp("RecFile").getLayout().setActiveItem(2);
                break;
            default:
                break;
        }

    },

    onTreepanelSelectionChange5: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');

        switch (xtype) {

            case 504:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('reclProc'));
                Ext.getCmp("ReclProc").getLayout().setActiveItem(3);
                break;


            case 701:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('MontCtrl'));
                jswCardStore = Ext.create('Ext.data.Store', {
                    id: 'CardStord',
                    proxy: {
                        // load using HTTP
                        type: 'ajax',
                        url: 'showCard.action',
                        // the return will be XML, so lets set up a reader
                        reader: {
                            type: "json",
                            root: "results",
                            totalProperty: 'totalCount'
                        },
                        actionMethods: {
                            read: 'POST'
                        },
                        writer: {
                            type: "json"
                        }
                    },
                    fields: [{
                            name: 'projectID',
                            type: 'string'
                        }, {
                            name: 'houseNumber',
                            type: 'string'
                        }, {
                            name: 'demolitionFlag',
                            type: 'string'
                        }, {
                            name: 'DLMC',
                            type: 'string'
                        }, {
                            name: 'DYNHSFZ',
                            type: 'string'
                        }, {
                            name: 'DYNHXM',
                            type: 'string'
                        }, {
                            name: 'FWJG',
                            type: 'string'
                        }, {
                            name: 'FWSYSJ',
                            type: 'string'
                        }, {
                            name: 'QSDWMC',
                            type: 'string'
                        }, {
                            name: 'SFDYXZSJ',
                            type: 'string'
                        }, {
                            name: 'FWZP',
                            type: 'string'
                        }, {
                            name: 'joinFlag',
                            type: 'string'
                        }, {
                            name: 'shape_Area',
                            type: 'auto'
                        },

                    ]
                });

                jswCardStore.load({
                    callback: function(records, options, success) {

                        Ext.getCmp("MontCtrl").getLayout().setActiveItem(0);

                        if (document.getElementById("jsMontMap")) {
                            var e = document.getElementById("jsMontMap");
                            e.parentNode.removeChild(e);
                            var head = document.getElementsByTagName('head')[0];
                            var script = document.createElement("script");
                            script.id = "jsMontMap";
                            script.type = "text/javascript";
                            script.src = "MyMap/WarmMap.js";
                            head.appendChild(script);
                        } else {
                            var head = document.getElementsByTagName('head')[0];
                            var script = document.createElement("script");
                            script.id = "jsMontMap";
                            script.type = "text/javascript";
                            script.src = "MyMap/WarmMap.js";
                            head.appendChild(script);
                        }

                    }
                });
                break;
            case 702:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('MontCtrl'));
                Ext.getCmp("MontCtrl").getLayout().setActiveItem(1);
                break;
            case 703:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('MontCtrl'));
                Ext.getStore('montAZ').load({
                    params: {
                        start: 0,
                        limit: 2,
                        categoryAZ: "安置监测"
                    }
                });
                Ext.getCmp("allMontAZ").setActiveTab(0);
                Ext.getCmp("MontCtrl").getLayout().setActiveItem(2);
                break;

            case 801:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('preWarm'));
                Ext.getCmp("RecWarm").getLayout().setActiveItem(0);
                break;
            case 802:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('preWarm'));
                Ext.getCmp("RecWarm").getLayout().setActiveItem(1);
                break;

            case 1001:
                tabPanel.removeAll(true);
                tabPanel.add(Ext.widget('efctEvlu'));
                var projectionStore = Ext.create('Ext.data.ArrayStore', {
                    proxy: {
                        type: "ajax",
                        url: "showProject.action",

                        reader: {
                            type: "json",
                            root: "results",
                            totalProperty: 'totalCount'
                        },
                        actionMethods: {
                            read: 'POST'
                        },
                        writer: {
                            type: "json"
                        }
                    },
                    fields: [{
                        name: 'id',
                        type: 'auto'
                    }, {
                        name: 'projectNumber',
                        type: 'string'
                    }, {
                        name: 'projectAddress',
                        type: 'string'
                    }, {
                        name: 'createTime',
                        type: 'date'
                    }, {
                        name: 'projectStatus',
                        type: 'string'
                    }, {
                        name: 'endTime',
                        type: 'date'
                    }, {
                        name: 'projectDescription',
                        type: 'string'
                    }, ],

                });
                projectionStore.load();
                var projectionPanel = Ext.create('Ext.grid.Panel', {
                    emptyText: '没有项目可选择',
                    region: 'center',
                    allowDeselect: true,
                    columnLines: true,
                    store: projectionStore,
                    columns: [{
                            xtype: 'gridcolumn',
                            width: 75,
                            align: 'center',
                            dataIndex: 'projectNumber',
                            text: '项目编号'
                        }, {
                            xtype: 'gridcolumn',
                            width: 150,
                            align: 'center',
                            dataIndex: 'projectAddress',
                            text: '项目所在地'
                        }, {
                            xtype: 'datecolumn',
                            width: 75,
                            align: 'center',
                            dataIndex: 'createTime',
                            text: '立项时间'
                        }, {
                            xtype: 'gridcolumn',
                            width: 150,
                            align: 'center',
                            dataIndex: 'projectDescription',

                            text: '项目描述'
                        },

                    ],

                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    })
                });
                var projectionWindow = Ext.create('Ext.window.Window', {
                    title: '请选择项目',
                    width: 600,

                    height: 400,
                    layout: {
                        type: 'border',
                    },
                    items: [{
                        xtype: 'panel',
                        layout: 'hbox',
                        region: 'south',
                        items: [{

                            xtype: 'button',
                            text: '确定',
                            handler: function() {
                                if (projectionPanel.getSelectionModel().hasSelection()) {
                                    var records = projectionPanel.getSelectionModel().getSelection();
                                    jsEvaluteProjectID = records[0].get('projectNumber');

                                    Ext.getCmp('evluProjecID').setValue(jsEvaluteProjectID);
                                    projectionWindow.destroy();
                                } else {
                                    Ext.Msg.alert('提示', "请选择一个项目");
                                }

                            },
                            width: 70,

                        }, {
                            xtype: 'button',
                            text: '取消',
                            handler: function() {
                                projectionWindow.destroy();
                            },
                            width: 70,
                        }, ]
                    }]
                });
                projectionWindow.add(projectionPanel);
                projectionWindow.show();

                Ext.getCmp("EfctEvlu").getLayout().setActiveItem(0);
                var head = document.getElementsByTagName('head')[0];
                var script = document.createElement("script");
                script.type = "text/javascript";
                script.src = "MyMap/FinalMap.js";
                head.appendChild(script);
                break;
            default:
                break;

        }

    },

    onTreepanelSelectionChange6: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange7: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange8: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange2: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        //Ext.MessageBox.alert('xtype',xtype);
        //var tabPanel=Ext.ComponentQuery.query('tabpanel')[0];

        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
        // Ext.MessageBox.alert('info444',title);

    },

    onTreepanelSelectionChange10: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelBeforeExpand: function(p, animate, eOpts) {
        var treeid = p.getId();

        Ext.Ajax.request(
        {
            url : 'get_UserRightList',
            params :
            {
                url : treeid
            },
            success : function (response){
                var result=Ext.decode(response.responseText);
                //console.log(result);
                if(!result){
                    Ext.Msg.alert('权限不足', '您没有权限进行此操作');
                    p.disable();
                }
            },
            failure : function (response){
                Ext.Msg.alert('权限不足', '您没有权限进行此操作');
                p.collapse();
                p.disable();
            }
        });


    },

    onMyViewPortAfterRender: function(component, eOpts) {
        //console.log('用户');
        Ext.Ajax.request({
            url:'get_loginUsername',
            //params:{articleIds:articleIds},

            success:function(response){
                //console.log('success','spring security');
                var result=Ext.decode(response.responseText);
                var username = result.username;
                //console.log('username',username);
                var btnuser = Ext.getCmp('btn_username');
                btnuser.setText(username);
                //var mystore = Ext.StoreMgr.get('ArticleRecJYXCStore');
                //mystore.load();
                //var mystore2 = Ext.StoreMgr.get('ArticlePubJYXCStore');
                //mystore2.load();
            }
        });

        //拦截器
        Ext.Ajax.on('requestexception', function (conn, response, options) {
            //console.log('拦截器');
            //console.log('response:',response);
            if (response.status === 403) {
                Ext.Msg.alert('权限不足', '您没有权限进行此操作');
                //window.location = 'accessDenied.jsp';
            }
        });

        //监听事件
        //var view = Ext.getCmp('btn_username');
        //Ext.util.Observable.capture(view, function(){
        //    console.log(view,arguments);
        //});

        //Ext.Ajax.on('requestcomplete', function (conn, response, options) {
        //console.log('事件监听',conn,response);
        //console.log('response:',response);
        //if (response.status === 403) {
        //    Ext.Msg.alert('权限不足', '您没有权限进行此操作');
        //    //window.location = 'accessDenied.jsp';
        //}
        //});
    }

});