/*
 * File: app/view/project_file_window.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.project_file_window', {
    extend: 'Ext.window.Window',
    alias: 'widget.project_file_window',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.Img'
    ],

    height: 400,
    id: 'project_file_window',
    width: 600,
    autoScroll: true,
    layout: 'column',
    title: '项目资料',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'form',
                            height: 25,
                            items: [
                                {
                                    xtype: 'filefield',
                                    anchor: '100%',
                                    buttonOnly: true,
                                    buttonText: '上传资料'
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '废弃房屋',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/01_01.jpg',
                            title: '废弃房屋',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '荒山',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/01_02.jpg',
                            title: '荒山',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender5,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '倒塌房屋',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/01_03.jpg',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender4,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '空心村',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/01_04.jpg',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender3,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '复垦项目实施方案',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/word.jpg',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender2,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '复垦项目技术设计',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/word.jpg',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender1,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '复垦工程表',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/excel.jpg',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender11,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 120,
                    html: '<div style="width:100%;height:100%;" background-image: url(project/word.jpg);',
                    margin: '5,5,5,5',
                    width: 100,
                    layout: 'fit',
                    title: '复垦项目台账',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            maxHeight: 100,
                            maxWidth: 100,
                            minHeight: 100,
                            minWidth: 100,
                            width: 100,
                            src: 'project/excel.jpg',
                            listeners: {
                                afterrender: {
                                    fn: me.onImageAfterRender111,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onImageAfterRender: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/01_01.jpg', '_blank');
        });
    },

    onImageAfterRender5: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/01_02.jpg', '_blank');
        });
    },

    onImageAfterRender4: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/01_03.jpg', '_blank');
        });
    },

    onImageAfterRender3: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/01_04.jpg', '_blank');
        });
    },

    onImageAfterRender2: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/doc_fangan.htm', '_blank');
        });
    },

    onImageAfterRender1: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/doc_shejishu.htm', '_blank');
        });
    },

    onImageAfterRender11: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/xls_gongcheng.htm', '_blank');
        });
    },

    onImageAfterRender111: function(component, eOpts) {
        component.el.on('click', function(){
            window.open('./project/xls_taizhang.htm', '_blank');
        });
    }

});