/*
 * File: app/view/projectionFile.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.projectionFile', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.projectionFile',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    id: 'projectionFile',
    layout: 'border',
    title: '项目资料管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    split: true,
                    store: 'projection_Store',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectNumber',
                            text: '项目编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectAddress',
                            text: '项目地址'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'createTime',
                            text: '创建时间'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'projectStatus',
                            text: '项目阶段'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'files',
                            text: '项目描述'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'projection_Store'
                        }
                    ],
                    listeners: {
                        cellclick: {
                            fn: me.onGridpanelCellClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        console.log("windowss");
        var win = Ext.widget('project_file_window');
        console.log("win:",win);
        if(win){
            console.log("win show");
            win.show();
        }
    }

});