/*
 * File: app/view/project_file_window.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.project_file_window', {
    extend: 'Ext.window.Window',
    alias: 'widget.project_file_window',

    requires: [
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.form.Panel',
        'Ext.form.field.File'
    ],

    height: 400,
    id: 'project_file_window',
    width: 600,
    autoScroll: true,
    layout: 'column',
    title: '项目资料',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    height: 201,
                    margin: '5,5,5,5',
                    maxHeight: 100,
                    maxWidth: 100,
                    minHeight: 100,
                    minWidth: 100,
                    width: 100,
                    src: 'images/project/01_01.JPG'
                },
                {
                    xtype: 'image',
                    height: 201,
                    margin: '5,5,5,5',
                    maxHeight: 100,
                    maxWidth: 100,
                    minHeight: 100,
                    minWidth: 100,
                    width: 100,
                    src: 'images/project/01_02.JPG'
                },
                {
                    xtype: 'image',
                    height: 201,
                    margin: '5,5,5,5',
                    maxHeight: 100,
                    maxWidth: 100,
                    minHeight: 100,
                    minWidth: 100,
                    width: 100,
                    src: 'images/project/01_03.JPG'
                },
                {
                    xtype: 'image',
                    height: 201,
                    margin: '5,5,5,5',
                    maxHeight: 100,
                    maxWidth: 100,
                    minHeight: 100,
                    minWidth: 100,
                    width: 100,
                    src: 'images/project/01_04.JPG'
                },
                {
                    xtype: 'image',
                    height: 201,
                    margin: '5,5,5,5',
                    maxHeight: 100,
                    maxWidth: 100,
                    minHeight: 100,
                    minWidth: 100,
                    width: 100,
                    src: 'images/project/word.JPG'
                },
                {
                    xtype: 'image',
                    height: 201,
                    margin: '5,5,5,5',
                    maxHeight: 100,
                    maxWidth: 100,
                    minHeight: 100,
                    minWidth: 100,
                    width: 100,
                    src: 'images/project/word.JPG'
                },
                {
                    xtype: 'image',
                    height: 201,
                    margin: '5,5,5,5',
                    maxHeight: 100,
                    maxWidth: 100,
                    minHeight: 100,
                    minWidth: 100,
                    width: 100,
                    src: 'images/project/excel.JPG'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'form',
                            height: 25,
                            items: [
                                {
                                    xtype: 'filefield',
                                    anchor: '100%',
                                    buttonOnly: true,
                                    buttonText: '上传资料'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});